Repository ECC-puro-ken/2024-11-19, pull requests merged in 2024-11, with the labels that each got.

#6 設定画面の作成
  src/pages/setting/index.tsx
Labels: good first issue, question

#2 カレンダー画面の追加
  src/pages/clender/index.tsx
  test/pages/index.test.tsx
Labels: bug, duplicate

#5 予約機能の追加
  src/pages/reservation/index.tsx
Labels: bug, documentation, invalid

#7 スプラッシュ画面の追加
  src/pages/splash/index.tsx
Labels: question

#4 PostAPIの追加
  src/pages/PostAPI/index.tsx
Labels: bug, help wanted, invalid

#3 プロフィール画面の追加
  src/pages/profile/index.tsx
Labels: enhancement, invalid, question
